server:
  port: 12345

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kopring
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      file: ./docker/docker-compose.yml
      lifecycle-management: start_only

infcon:
  location: coex
  date: 2023-08-15
  url: https://inflearn.com/conf/infcon-2023
